Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cff7528ff583bf9a
      Tags: 
       - Key: "Name"
         Value: !Join 
                - " "
                - - "my instance in"
                  - !Ref AWS::Region 
      SecurityGroups: 
        - !Ref testingsg   
  testingsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http to client host
      VpcId: Ref: vpc-47b7323a
      SecurityGroupIngress:
      - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      